//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoPizza.AppServises
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int Sum { get; set; }
        public Nullable<int> Id_Pizza { get; set; }
        public Nullable<int> Id_Snacks { get; set; }
        public Nullable<int> Id_Deverages { get; set; }
        public Nullable<int> Id_Dessert { get; set; }
        public Nullable<int> Id_AddProducts { get; set; }
    
        public virtual AddProducts AddProducts { get; set; }
        public virtual Dessert Dessert { get; set; }
        public virtual Deverages Deverages { get; set; }
        public virtual Pizza Pizza { get; set; }
        public virtual Snacks Snacks { get; set; }
    }
}
